---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-updater
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ecr-updater
  labels:
    k8s-app: ecr-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ecr-updater
  template:
    metadata:
      labels:
        k8s-app: ecr-updater
        name: ecr-updater
    spec:
      serviceAccountName: ecr-updater
      containers:
      - image: trondhindenes/k8s-ecrupdater
        name: ecrupdater
        env:
        - name: K8S_PULL_SECRET_NAME
          valueFrom:
            configMapKeyRef:
              name: ecr-updater-config
              key: aws.secret-name
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: ecr-updater-config
              key: aws.region
        - name: ECR_UPDATE_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: ecr-updater-config
              key: ecr-update-interval
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: ecr-aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ecr-aws-credentials
              key: AWS_SECRET_ACCESS_KEY
      - image: lachlanevenson/k8s-kubectl
        name: kubectl-proxy
        args: ["proxy", "--port=8001"]
